<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateRecruitmentsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('recruitments', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('guild_id')->nullable();
            $table->integer('user_id');
            $table->integer('realm_id')->nullable();
            $table->string('title', 191);
            $table->text('body')->nullable();
            $table->integer('number')->nullable();
            $table->integer('class_id')->nullable();
            $table->integer('classrole_id')->nullable();
            $table->tinyInteger('status')->nullable();
            $table->nullableTimestamps();
            $table->softDeletes();





        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('recruitments');
    }
}
