<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateKillsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('kills', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('character_id');
            $table->integer('boss_id')->nullable();
            $table->integer('raid_id')->nullable();
            $table->integer('lfrKills')->nullable();
            $table->string('lfrTimestamp', 191)->nullable();
            $table->integer('normalKills')->nullable();
            $table->string('normalTimestamp', 191)->nullable();
            $table->integer('heroicKills')->nullable();
            $table->string('heroicTimestamp', 191)->nullable();
            $table->integer('mythicKills')->nullable();
            $table->string('mythicTimestamp', 191)->nullable();
            $table->nullableTimestamps();





        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('kills');
    }
}
